apiVersion: skaffold/v1beta11
kind: Config
deploy:
  helm:
    releases:
      - name: hello-world
        wait: true
        chartPath: ./hello-world
        setValueTemplates:
          productName: "{{.PRODUCT_NAME}}"
          "ingress.domain": "{{.PRODUCT_NAME}}-hello-world.{{.DOMAIN}}"
          "ingress.class": "{{.ENVIRONMENT}}-app-nginx"
        setValues:
          https: true
profiles:
  - name: dev
    patches:
      - op: replace
        path: /deploy/helm/releases/0/setValueTemplates/domain
        value: "istio.localhost"
      - op: replace
        path: /deploy/helm/releases/0/setValueTemplates/https
        value: false
