apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.appName }}
              servicePort: 5555
