{{ if .Values.enableVirtualservice }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
    - {{ .Chart.Name }}-{{ .Values.productName }}.{{ .Values.istioDomain }}
  gateways:
    - "istio-system/app-gateway"
  http:
    - route:
        - destination:
            host: {{ .Values.appName }}
            port:
              number: 5555
{{- end }}
