apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ .Chart.Name }}.{{ .Values.istioDomain }}
      port:
        name: http
        number: 80
        protocol: HTTP
{{- if eq .Values.https true }}
      tls:
        httpsRedirect: true
    - hosts:
        - {{ .Chart.Name }}.{{ .Values.istioDomain }}
      port:
        name: https-default
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: "sds"
        privateKey: "sds"
        credentialName: "{{ .Release.Namespace }}-certificate"
{{- end }}
