apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    foo: bar
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5555
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
