apiVersion: v1
kind: Service
metadata:
  name: hello-world-canary
  labels:
    app: hello-world-canary
    foo: bar
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5555
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hello-world-canary
