apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
    - {{ .Chart.Name }}.{{ .Values.istioDomain }}
  gateways:
    - "{{ .Chart.Name }}-gateway"
  http:
    - route:
        - destination:
            host: {{ .Values.appName }}
            port:
              number: 5555
